application:
  host: "0.0.0.0"
  app_url: "https://toki.spinit.se"
  api_url: "https://toki-api.spinit.se"
  cookie_domain: ".spinit.se"
  disable_auth: false
  cors_allowed_origin_suffix: "-ponbacs-projects.vercel.app"
database:
  require_ssl: true
auth:
  redirect_url: "https://toki-api.spinit.se/oauth/callback"
